apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: hello-gitops
  labels:
    app: hello-app
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: hello-app
    version: v1.0.0
  type: ClusterIP